os: Visual Studio 2015

before_build:
  # download and unzip sources
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-2.0.3.zip
  - 7z x SDL2-2.0.3.zip > nul
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.0.zip
  - 7z x SDL2_net-2.0.0.zip > nul
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.zip
  - 7z x SDL2_mixer-2.0.0.zip > nul
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.zip
  - 7z x SDL2_image-2.0.0.zip > nul
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.zip
  - 7z x SDL2_ttf-2.0.12.zip > nul
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.zip
  - 7z x SDL2_image-2.0.1.zip > nul
  # patch sources for vs2015 build (it will disable xaudio support)
  - ps: (Get-Content SDL2-2.0.3\src\audio\xaudio2\SDL_xaudio2.c) | Foreach-Object {$_ -replace "#include <dxsdkver.h>","//#include <dxsdkver.h>"} | Set-Content SDL2-2.0.3\src\audio\xaudio2\SDL_xaudio2.c
  # copy prepared VS2015 solution and project files
  - copy SDL_VS2015.sln SDL2-2.0.3\VisualC\SDL_VS2015.sln
  - copy SDL_VS2015.vcxproj SDL2-2.0.3\VisualC\SDL\SDL_VS2015.vcxproj
  - copy SDLmain_VS2015.vcxproj SDL2-2.0.3\VisualC\SDLmain\SDLmain_VS2015.vcxproj
  # SDL_net
  - copy SDL_net_VS2015.sln SDL2_net-2.0.0\VisualC\SDL_net_VS2015.sln
  - copy SDL_net_VS2015.vcxproj SDL2_net-2.0.0\VisualC\SDL_net_VS2015.vcxproj
  - copy showinterfaces_VS2015.vcxproj SDL2_net-2.0.0\VisualC\showinterfaces\showinterfaces_VS2015.vcxproj
  # SDL_mixer
  - copy SDL_mixer_VS2015.sln SDL2_mixer-2.0.0\VisualC\SDL_mixer_VS2015.sln
  - copy SDL_mixer_VS2015.vcxproj SDL2_mixer-2.0.0\VisualC\SDL_mixer_VS2015.vcxproj
  - copy native_midi_VS2015.vcxproj SDL2_mixer-2.0.0\VisualC\native_midi\native_midi_VS2015.vcxproj
  - copy playmus_VS2015.vcxproj SDL2_mixer-2.0.0\VisualC\playmus\playmus_VS2015.vcxproj
  - copy playwave_VS2015.vcxproj SDL2_mixer-2.0.0\VisualC\playwave\playwave_VS2015.vcxproj
  - copy timidity_VS2015.vcxproj SDL2_mixer-2.0.0\VisualC\timidity\timidity_VS2015.vcxproj
  # SDL_ttf
  - copy SDL_ttf_VS2015.sln SDL2_ttf-2.0.12\VisualC\SDL_ttf_VS2015.sln
  - copy SDL_ttf_VS2015.vcxproj SDL2_ttf-2.0.12\VisualC\SDL_ttf_VS2015.vcxproj
  - copy glfont_VS2015.vcxproj SDL2_ttf-2.0.12\VisualC\glfont\glfont_VS2015.vcxproj
  - copy showfont_VS2015.vcxproj SDL2_ttf-2.0.12\VisualC\showfont\showfont_VS2015.vcxproj
  # SDL_image
  - copy SDL_image_VS2015.sln SDL2_image-2.0.1\VisualC\SDL_image_VS2015.sln
  - copy SDL_image_VS2015.vcxproj SDL2_image-2.0.1\VisualC\SDL_image_VS2015.vcxproj
  - copy showimage_VS2015.vcxproj SDL2_image-2.0.1\VisualC\showimage\showimage_VS2015.vcxproj
  # collect licenses
  - md licences
  - copy SDL2-2.0.3\COPYING.txt licences\COPYING.SDL2.txt
  - copy SDL2_image-2.0.1\COPYING.txt licences\COPYING.SDL2_image.txt
  - copy SDL2_mixer-2.0.0\COPYING.txt licences\COPYING.SDL2_mixer.txt
  - copy SDL2_net-2.0.0\COPYING.txt licences\COPYING.SDL2_net.txt
  - copy SDL2_ttf-2.0.12\COPYING.txt licences\COPYING.SDL2_ttf.txt
  # collect includes
  - md include
  - md include\SDL2
  - copy SDL2-2.0.3\include\*.* include\SDL2
  - copy SDL2_image-2.0.1\SDL_image.h include\SDL2
  - copy SDL2_mixer-2.0.0\SDL_mixer.h include\SDL2
  - copy SDL2_net-2.0.0\SDL_net.h include\SDL2
  - copy SDL2_ttf-2.0.12\SDL_ttf.h include\SDL2

build_script:
  - msbuild "SDL2-2.0.3\VisualC\SDL_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform=x86
  - msbuild "SDL2-2.0.3\VisualC\SDL_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Debug /p:Platform=x86
  - msbuild "SDL2_net-2.0.0\VisualC\SDL_net_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform=Win32
  - msbuild "SDL2_net-2.0.0\VisualC\SDL_net_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Debug /p:Platform=Win32
  - msbuild "SDL2_mixer-2.0.0\VisualC\SDL_mixer_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform=Win32
  - msbuild "SDL2_mixer-2.0.0\VisualC\SDL_mixer_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Debug /p:Platform=Win32
  - msbuild "SDL2_ttf-2.0.12\VisualC\SDL_ttf_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform=x86
  - msbuild "SDL2_ttf-2.0.12\VisualC\SDL_ttf_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Debug /p:Platform=x86
  - msbuild "SDL2_image-2.0.1\VisualC\SDL_image_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform=x86
  - msbuild "SDL2_image-2.0.1\VisualC\SDL_image_VS2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Debug /p:Platform=x86

after_build:
  - 7z a sdl2.zip -i@"release.txt"
  - 7z a sdl2d.zip -i@"debug.txt"

artifacts:
  - path: sdl2.zip
    name: sdl2
  - path: sdl2d.zip
    name: sdl2d

deploy:
  provider: GitHub
  release: SDL2-Binaries
  description: 'SDL2 mvsc binaries'
  auth_token:
    secure: FLLAgKct3M0RM2UAGxPMC3CazyD4SyNVh4X3gdB8T1PHYtTvXJOYqG4D+6R9iKop
  artifact: sdl2, sdl2d
  draft: false
  prerelease: false
  on:
    branch: master
