os: Visual Studio 2015

matrix:
  fast_finish: true
  
platform:
  - Win32

configuration:
  - Release

before_build:
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-2.0.3.zip
  - 7z x SDL2-2.0.3.zip > nul
  - copy SDL_VS2015.sln SDL2-2.0.3\VisualC\SDL_VS2015.sln

build:
  project: SDL2-2.0.3\VisualC\SDL_VS2015.sln

after_build:
  - 7z a sdl2.zip .\SDL2-2.0.3\VisualC\SDL\Win32\Release\SDL2.lib .\SDL2-2.0.3\VisualC\SDL\Win32\Release\SDL2.dll .\SDL2-2.0.3\VisualC\SDLmain\Win32\Release\SDL2main.lib

artifacts:
  - path: sdl2.zip
    name: sdl2

deploy:
  provider: GitHub
  release: sdl2-binaries
  description: 'SDL2 mvsc binaries'
  auth_token:
    secure: FLLAgKct3M0RM2UAGxPMC3CazyD4SyNVh4X3gdB8T1PHYtTvXJOYqG4D+6R9iKop
  artifact: sdl2
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: false
